// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfddfgbtgeziqztpllqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmZGRmZ2J0Z2V6aXF6dHBsbHFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzQ3NjQsImV4cCI6MjA2NjAxMDc2NH0.nD34DH76PCqKc3oMQSEvuzyRhw-b8-CNH8m9z53mSig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});