// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjjuyylfokhzbidlbnqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qanV5eWxmb2toemJpZGxibnF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzQ5MzEsImV4cCI6MjA2NjAxMDkzMX0.tSf91saqBDT363_qZV0NpSI8nKqK3Y8sXjJKehAbHnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);